version: 2.1

jobs:
  build-image:
    machine:
      docker_layer_caching: true
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: |
          docker build --tag aptgetexplore .
 
workflows:
  docker:
    jobs:
      - build-image
